spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:23127/railway
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update